### ISSUE TITLE
[bug] El titulo lo corta

### ISSUE THREAD

**Issue by joseEnrique** [politicalwatch/tipi-engine#39]
Los parentesis estan en mitad del titulo

http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas/Indice%20de%20Iniciativas?_piref73_1335503_73_1335500_1335500.next_page=/wc/servidorCGI&CMD=VERLST&BASE=IW12&PIECE=IWC2&FMT=INITXD1S.fmt&FORM1=INITXLUS.fmt&DOCS=47-47&QUERY=%28I%29.ACIN1.+%26+%28162%29.SINI.

**Comment by pr3ssh** [comment]
@joseEnrique qué hacemos con esto?
